cataloger/annotations/views.py
# -*- coding: utf-8 -*-
"""annotation views."""
import os
import requests
import tempfile
import logging
from datetime import datetime

from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    flash,
    url_for,
    send_file,
    current_app,
)

from flask_login import login_required, current_user

from cataloger.annotations.forms import NewCardForm, EditCardForm, ManageAnnotationForm

from cataloger.annotations.models import (
    Card,
    Organism,
    Process,
    Sample,
    Marker,
    Gene,
    Method,
    Project,
    GeneMod,
    get_gene_mod,
)


from cataloger.utils import get_url_prefix

log = logging.getLogger(__name__)

# https://bioportal.bioontology.org/help#Getting_an_API_key

BIOPORTAL_API_KEY = os.environ.get("BIOPORTAL_API_KEY")
if not BIOPORTAL_API_KEY:
    raise ValueError(
        """
To use this service, you need an API key provided
by bioportal here: https://bioportal.bioontology.org/help#Getting_an_API_key,
this key should then be stored as the environement variable BIOPORTAL_API_KEY
"""
    )


classes = {
    "organisms": Organism,
    "processes": Process,
    "samples": Sample,
    "markers": Marker,
    "genes": Gene,
    "methods": Method,
}


blueprint = Blueprint(
    "cards",
    __name__,
    url_prefix=get_url_prefix("cards"),
    static_folder="../static",
)

ontologies = {
    classes["organisms"]: ("NCBITAXON",),
    classes["samples"]: ("FB-BT", "GO", "MESH", "CLO", "NCIT"),
    classes["processes"]: ("GO", "MESH", "NCIT"),
    classes["methods"]: ("FBbi", "EDAM-BIOIMAGING", "MESH", "NCIT"),
    classes["genes"]: ("FBbi", "EDAM-BIOIMAGING", "GO"),
    classes["markers"]: ("FBbi", "GO", "EDAM-BIOIMAGING", "PR"),
}


def new_project(form):
    match = Project.query.filter_by(
        label=form.new.data, group_id=current_user.group_id
    ).first()
    if match:
        flash(f"Project {match.label} already exists", "warning")
        return match

    project = Project(
        label=form.new.data,
        user_id=current_user.id,
        group_id=current_user.group_id,
    )
    flash(f"New project {project.label} created by user {current_user.id}", "success")
    project.save()
    form.select.choices.insert(0, (project.id, project.label))
    return project


def search_bioportal(search_text, **other_params):
    """Searches the bioontology database for the term search_text"""

    params = {
        "apikey": BIOPORTAL_API_KEY,
        "q": search_text,
        "suggest": False,
    }
    params.update(other_params)
    response = requests.get(f"http://data.bioontology.org/search", params=params).json()
    if "errors" in response:
        flash(f'Invalid search, response["errors"]')
        return {}

    return {term["@id"]: term for term in response["collection"]}


def annotation_choices(kls, search_term=None):
    if search_term is None:
        search_term = request.args.get("search_term")

    suggestions = search_bioportal(search_term, ontologies=",".join(ontologies[kls]))

    uniq = {_format_label(term): term_id for term_id, term in suggestions.items()}
    choices = [(v, k) for k, v in uniq.items()]
    return suggestions, choices


def new_annotation(kls, term, card_id=None):
    """New annotation from a bioportal search result"""

    match = kls.query.filter_by(label=term["prefLabel"]).first()
    if match:
        flash(f"The term {term['prefLabel']} is already registered", "warning")
        if match.group_id == current_user.group_id:
            return match
        term["@id"] = match.bioportal_id  # use the same ref

    if kls is Organism:
        new = kls(
            label=term["prefLabel"],
            bioportal_id=term["@id"],
            user_id=current_user.id,
            group_id=current_user.group_id,
        )
        new.save()
        flash(f"Term {term['prefLabel']} registered", "success")
        return new

    card = Card.get_by_id(card_id)

    organism_id = card.organism_id if card else 1
    if not card:
        organism = Organism.get_by_id(1)
        if not organism:
            default_organism = Organism(
                label="Unknown",
                bioportal_id="default",
                user_id=1,
                group_id=1,
            )
            default_organism.save()
        organism_id = 1

    new = kls(
        label=term["prefLabel"],
        bioportal_id=term["@id"],
        organism_id=organism_id,
        user_id=current_user.id,
        group_id=current_user.group_id,
    )
    flash(f"Term {term['prefLabel']} registered", "success")

    new.save()
    return new


def _format_label(term, show_definition=False, nwords=8):
    label = term["prefLabel"]
    ontology_id = term["links"]["ontology"]
    definition = term.get("definition")
    ontology = ontology_id.split("/")[-1]
    if show_definition and definition:
        split = definition[0].split()
        if len(split) > nwords:
            short = " ".join(split[:nwords]).split(".")[0] + " ..."
        else:
            short = definition
        return f"{label}: {short} \t ({ontology})"
    else:
        return f"{label} \t ({ontology})"


@blueprint.route("/")
@login_required
def cards(scope="group"):
    """List cards"""
    if scope == "user":
        user_id = current_user.id
        cards_ = Card.query.filter_by(user_id=user_id)
    elif scope == "group":
        cards_ = Card.query.filter(Card.group_id == current_user.group_id)
    else:
        cards_ = Card.query.all()
    return render_template("annotations/cards.html", cards=cards_)


def search_annotation(form, key, selector, card=None):

    search_term = selector.search.data
    log.info("searching for %s", search_term)
    suggestions, choices = annotation_choices(selector.kls, search_term=search_term)

    if not suggestions:
        flash(
            """Sorry, no results found. Please reformulate your query,
 maybe with more general terms, and check for typos""",
            "warning",
        )
        selector.search.data = search_term
        if card:
            return render_template(
                "annotations/new_card.html", form=form, card_id=card.id, search=key
            )
        return render_template("annotations/new_card.html", form=form)

    current_app.suggestions = suggestions
    form.update_choices(group_id=current_user.group_id)
    selector.select_new.choices = choices
    if card:
        return render_template(
            "annotations/edit_card.html", form=form, new=key, card_id=card.id
        )
    return render_template("annotations/new_card.html", form=form, new=key)


def add_annotation(form, key, selector, card=None):

    if selector.free:
        # mock the result of a bioportal request
        term = {"prefLabel": selector.new.data, "@id": "local term"}

    else:
        if not hasattr(current_app, "suggestions"):
            if card:
                return redirect(
                    url_for("cards.edit_card", card_id=form.card_id, search=key)
                )
            return render_template("annotations/new_card.html", form=form, search=key)
        try:
            term = current_app.suggestions[selector.select_new.data]
        except KeyError:
            log.error(
                "Suggestion %s not found in suggestions %s",
                term,
                list(current_app.suggestions.keys()),
            )
            if card:
                return redirect(url_for("cards.edit_card", card_id=form.card_id))
            return render_template("annotations/new_card.html", form=form, search=key)

    new = new_annotation(selector.kls, term)

    selector.choices.insert(0, (new.id, new.label))
    selector.data = new.id

    if selector.kls in (Gene, Marker):
        idx = int(key.split("_")[-1])
        gene_id = form.selectors[f"gene_{idx}"].data
        marker_id = form.selectors[f"marker_{idx}"].data
        gene_mod = get_gene_mod(gene_id, marker_id)
        if card:
            if len(card.gene_mods) > idx:
                card.gene_mods[idx] = gene_mod
            else:
                card.gene_mods.append(gene_mod)
            card.save()
            return redirect(url_for("cards.edit_card", card_id=form.card_id))
        return render_template("annotations/new_card.html", form=form)

    if card:
        term_id = selector.kls.__name__.lower() + "_id"
        setattr(card, term_id, new.id)
        card.save()
        return redirect(url_for("cards.edit_card", card_id=form.card_id))
    return render_template("annotations/new_card.html", form=form)


@blueprint.route(
    "/edit/<card_id>",
    methods=["GET", "POST"],
    defaults={"card_id": 0, "new": "none", "search": "none"},
)
@blueprint.route(
    "/edit/<card_id>",
    methods=["GET", "POST"],
)
@login_required
def edit_card(card_id, search=None, new=None):

    card = Card.query.filter_by(id=card_id).first()
    if card.user_id != current_user.id:
        flash("You can only edit your own cards, consider cloning instead", "warning")
        return redirect(url_for("user.cards"))
    form = EditCardForm(card_id=card_id)
    form.update_choices(group_id=current_user.group_id)

    if form.cancel.data:
        flash("Canceled", "warning")
        return render_template(
            "annotations/edit_card.html",
            form=form,
            search=search,
            new=new,
            card_id=card_id,
        )
    for key, selector in form.selectors.items():
        if selector.new.data:
            return add_annotation(form, key, selector, card)

    for key, selector in form.selectors.items():
        if selector.search.data:
            return search_annotation(form, key, selector, card)

    for key, selector in form.selectors.items():
        if selector.select_new.data:
            return add_annotation(form, key, selector, card)

    for key, selector in form.selectors.items():
        if selector.add.data:
            log.info("searching for new %s", key)
            return render_template(

cataloger/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

cataloger/templates/_formhelpers.html
{% macro render_field(field) %}
    <dt>{{ field.label }}
    </dt><dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
        <ul class="errors">
        {% for error in field.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    </dd>
{% endmacro %}

cataloger/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Guillaume Gay</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:guillaume.gay.1@univ-amu.fr">Contact</a></li>
    </ul>
  </small>
</footer>

cataloger/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <script src="https://kit.fontawesome.com/11eb352f8d.js" crossorigin="anonymous"></script>

    <link rel="shortcut icon" href="{{static_url_for('public.static', filename='build/img/favicon.ico') }}">
    <title>
      {% block page_title %}
      Cataloger
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('public.static', filename='build/main_css.bundle.css') }}"
    />

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert"
              >&times;</a
            >
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ static_url_for('public.static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

cataloger/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     Cataloger
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('public.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      {% if current_user and current_user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('cards.new_card') }}">New card</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.cards') }}">My cards</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('cards.cards') }}">All cards</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.cards') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="{{ url_for('public.home') }}" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>